version: '3.8'

services:
  app:
    build: .
    ports:
      - "18000:8000"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./saved_models:/app/saved_models
      - ./notebooks:/app/notebooks
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload 