version: '3.8'

services:
  app:
    build: .
    ports:
      - "18000:8000"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./saved_models:/app/saved_models
      - ./notebooks:/app/notebooks
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload 
  redis:
    image: redis:7
    ports:
      - "6379:6379" 
  gradio:
    build:
      context: .
      dockerfile: Dockerfile.gradio
    ports:
      - "7860:7860"
    volumes:
      - ./src:/app/src
    depends_on:
      - app
      - redis 