version: '3.8'

services:
  api:
    build: .
    image: detector-api:latest
    container_name: detector-api
    ports:
      - "18000:8000"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./saved_models:/app/saved_models
      - ./notebooks:/app/notebooks
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload 
  redis:
    image: redis:7
    container_name: detector-redis
    ports:
      - "16379:6379" 
  gradio:
    build:
      context: .
      dockerfile: Dockerfile.gradio
    image: detector-gradio:latest
    container_name: detector-gradio
    ports:
      - "17860:7860"
    volumes:
      - ./src:/app/src
    command: python src/webui.py
    depends_on:
      - api
      - redis 