FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt ./
COPY src ./src

RUN pip install --no-cache-dir gradio requests && \
    pip install --no-cache-dir -r requirements.txt

EXPOSE 7860

CMD ["python", "src/webui.py"]
